### ISSUE TITLE
Change the exemple with Mockery ?

### ISSUE THREAD

**Issue by popod** [doublesharp/nodemailer-mock#15]
The Mockery project seems dead and untouched since 2017.

Add or change the existing exemple by using an other project will be great ! Something like [sinon.js](https://github.com/sinonjs/sinon) ?

**Comment by PhakornKiong** [comment]
I'm exploring using this library with jest. Would be more than happy to assist to update the document if the maintainer is interested. Let me know!

**Comment by doublesharp** [comment]
@Darkripper214 That would be great! I just don't have time to work on it right now but would be happy to update the documentation if you get it working. Thanks!

**Comment by doublesharp** [comment]
@popod @Darkripper214 I made an update to make the module more compatible with `jest` - the passthrough of the `transport.verify()` is not possible as the module is mocked before the mock module loads. In [version 1.5.5+](https://www.npmjs.com/package/nodemailer-mock) it checks to see if `nodemailer` is available and bypasses it if not - make sure to use this version with `jest` tests.

I also included some examples for both `jest` and `mocha` in the README and source code in [`./examples/`](https://github.com/doublesharp/nodemailer-mock/tree/master/examples). For `jest`, it would look something like the following:


```javascript
/** 
 * Jest Mock
 * ./__mocks__/nodemailer.js 
 **/
module.exports = require('nodemailer-mock');
```

```javascript
/** 
 * Jest Test
 * ./__tests__/my-test.js 
 **/
const { mock } = require('nodemailer');

test('Send an email using the mocked nodemailer', async () => {
  /* ... run your tests that send emails here */

  // check the mock for our sent emails
  const sentEmails = mock.getSentMail();
  // there should be one
  expect(sentEmails.length).toBe(1);
  // and it should match the to address
  expect(sentEmails[0].to).toBe('justin@to.com');
});
```

Let me know if you have any issues, thanks!

**Comment by PhakornKiong** [comment]
@doublesharp I was going to do update this weekend. Basically everything works fine for `jest` except for the `transport.verify()` due to the way mocking works.

I was going to ask if it is necessary to provide user ability to use the actual instance to do the `transport.verify()` in a test scenario?

**Comment by doublesharp** [comment]
@Darkripper214 I figured out how to do it... you will need to update to `nodemailer-mock@1.5.7+` to use the `.getMockFor()` method which will allow you to pass in the real `nodemailer` when the mock is loaded.


```javascript
/** 
 * Jest Mock
 * ./__mocks__/nodemailer.js 
 **/
// load the real nodemailer
const nodemailer = require('nodemailer');
// pass it in when creating the mock using getMockFor()
const nodemailerMock = require('nodemailer-mock').getMockFor(nodemailer);
// export the mocked module
module.exports = nodemailerMock;
```
