### ISSUE TITLE
Unwanted developer tools install

### ISSUE THREAD

**Issue by mkboice** [doublesharp/nodemailer-mock#2]
I installed and used this package. It works great but since it has developer-tools as a dependency, it wound up installing git hooks, and npm scripts as well as some .eslintrc, and other files. I didn't want the developer-tools package to install these files and settings. I imagine other's wouldn't want it either. 

Is the developer-tools package needed? If so, can a note be added to the README to mention that it uses the package and to expect some files and settings to be installed? Or even an option to add/remove the package?

Thanks

**Comment by doublesharp** [comment]
Sorry about that, you are correct that it shouldn't be modifying your project. 

I accidentally included the `developer-tools` module in the dependencies when upgrading it - it should only be in devDependencies. 

Please check out the version that I just pushed and it should be corrected, thanks!

**Comment by mkboice** [comment]
Awesome thanks!
