### ISSUE TITLE
TemplateSender support. 

### ISSUE THREAD

**Issue by dopry** [doublesharp/nodemailer-mock#3]
It would be nice if the template sender was also mockable.

**Comment by doublesharp** [comment]
Can you include an example of the code you're trying to mock?

**Comment by dopry** [comment]
```
var transporter = nodemailer.createTransport(...);
var send = transporter.templateSender(templates, [defaults]);

// send a message based on provided templates
send(mailData, context, callback);
// or
send(mailData, context).then(...).catch(...);
```

I ended up using the nodemailer-mock-transport to do some of my tests.. creating proper error cases was a challenge, but I was able to test the functionality.

**Comment by doublesharp** [comment]
This is a bit more work than I thought because this function renders the template internally before sending. Just adding the function to the mocked class is easy enough if all you care to see is the `mailData` that was passed, actually rendering the email is a bit harder.

**Comment by doublesharp** [comment]
closing as this functionality has been deprecated in nodemailer.
