### ISSUE TITLE
Installing nodemailer-mock changes package.json, git hooks and adds bunch of files to root folder

### ISSUE THREAD

**Issue by rnemec** [doublesharp/nodemailer-mock#4]
I don't think it is fair to silently install git hooks for pre-commit and pre-push as well as all the additional scripts added to our package.json.

**Comment by doublesharp** [comment]
Yikes, sorry about that. I accidentally included a development module in the dependencies in the latest version. I'm driving on roadtrip but if you want to submit a PR removing 'developer-tools' from dependencies (leave in devDependencies) I will approve it and you could just use that if you would like, or I can update it and the number repo once I can get on my laptop.
