### ISSUE TITLE
Add support for sendMail()'s Promise return value

### ISSUE THREAD

**Issue by dmitrizagidulin** [doublesharp/nodemailer-mock#6]
Nodemailer conveniently provides a Promise wrapper for `sendMail()` (see the note at the bottom of https://nodemailer.com/usage/, `If callback argument is not set then the method returns a Promise object.` 

The mock `sendMail()` only provides the callback-based interface, without the Promise wrapper.

Would you accept a PR to add the Promise wrapper, to have the same semantics as nodemailer's?

**Comment by doublesharp** [comment]
Definitely, I just haven't had time to work on it myself.

**Comment by doublesharp** [comment]
Added in [v1.3.0](https://www.npmjs.com/package/nodemailer-mock)

**Comment by dmitrizagidulin** [comment]
Wow, awesome!
