### ISSUE TITLE
The presence of npm-shrinkwrap.json making shrink wrapping fail at the root module

### ISSUE THREAD

**Issue by sravanrekandar** [doublesharp/nodemailer-mock#7]
Hi.
Thanks for providing this module.
Problem:
I am maintaining npm-shrinkwrap.json in my application. Now if I try install nodemailer-mock, my application's shrink wrapping is failing by giving many extraneous errors.
Example error:
npm WARN saveError extraneous: lodash.keys@3.1.2 /Users/sravankumarrekandar/workarea/nodemailer-test/node_modules/nodemailer-mock/node_modules/lodash.keys
..
The issue was fixed when I deleted both my-app/node_modules/nodemailer-mock/node_modules and  my-app/node_modules/nodemailer-mock/npm-shrinkwrap.json
Then reinstalled my-app dependencies.
And everything is working fine.

However, we cannot maintain the hack. Please make sure the module is compatible with other apps.

Thanks.

**Comment by doublesharp** [comment]
I was using this module in another shrinkwrapped project previously so I
don't think it's inherently incompatible. Did you try running "npm prune"
or "npm dedupe"?

That said, I had lots of issues with npm/shrinkwrap in general and ended up
moving everything to yarn, so I can probably remove the shrinkwrap file as
it's not being used. I'll check into it soon and will push an updated
version.

**Comment by doublesharp** [comment]
The `npm-shrinkwrap.json` file has been removed in version 1.2.2.
